---
aleph_x_url: http://mirlyn-aleph.lib.umich.edu
bib_library: MIU01
adm_library: MIU50
services:
  borrower:
    ill:
      - "01AF"
      - "01EM"
      - "01FA"
      - "01GE"
      - "01GF"
      - "01HH"
      - "01JF"
      - "01RF"
      - "01SE"
      - "01SW"
      - "01VS"
      - "02CR"
      - "02D1"
      - "02D2"
      - "02EP"
      - "02OJ"
      - "02RS"
      - "02ST"
      - "02WD"
      - "03GR"
      - "04SU"
      - "04UN"
    7fast:
      - "01AF"
      - "01EM"
      - "01FA"
      - "01GE"
      - "01GF"
      - "01HH"
      - "01JF"
      - "01RF"
      - "01SE"
      - "01SW"
      - "01VS"
      - "02CR"
      - "02D1"
      - "02D2"
      - "02EP"
      - "02OJ"
      - "02RS"
      - "02ST"
      - "02WD"
      - "03GR"
      - "04UN"
